### ISSUE TITLE
quota opensuse cron

### ISSUE THREAD

**Issue by Smiril** [frankuit/owncloud-nagios#1]
still not working on Opensuse 13.2

only show:      Mb used: allowed: 
with Warning Sign

**Comment by frankuit** [comment]
Hi Smiril,

If you just run the du.php on your owncloud installation, (after you've modified it) with the correct mysql data and the correct path to your owncloud userdata dir, what does the script return ?
So run it without using nagios first.

Regards,
Frank

**Comment by Smiril** [comment]
i´v found the problem thanks my fail
/home/data1/oc/owncloud/data/ that was the dir 

works great on OpenSuSe 13.2 with Nagios
